services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app:cached  # optimisation sur Windows
      - /app/node_modules       # empêche conflit de node_modules
    ports:
      - "3000:3000"
    environment:
      - API_BASE=http://backend:8000/api
    command: "npm run dev -- --host"
    depends_on:
      - backend

  backend:
    build: ./backend
    container_name: backend
    volumes:
      - ./backend:/var/www:cached
    environment:
      - DATABASE_URL=pgsql://app:!ChangeMe!@database:5432/app?serverVersion=15&charset=utf8
    depends_on:
      - database
    ports:
      - "8000:8000"

  database:
    image: postgres:15
    container_name: database
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    ports:
      - "8080:8080"

volumes:
  pgdata:
