services:
    App\State\NotificationProcessor:
        arguments:
            $persistProcessor: '@api_platform.doctrine.orm.state.persist_processor'
        tags:
            - { name: 'api_platform.state.processor' }
